name: scan_pay
description: 
  ScanPay é um pacote Flutter que oferece funcionalidades para escanear códigos QR de boletos bancários e pagamentos via Pix.
  Ele facilita a leitura e processamento de informações de pagamento em aplicativos Flutter, permitindo que os usuários
  façam pagamentos de forma rápida e conveniente.

  Principais recursos 
  - Escaneie códigos QR de boletos bancários e pagamentos Pix.
  - Extraia informações relevantes dos códigos escaneados.
  - Fornece uma interface simples para lidar com informações de pagamento.

  Este pacote foi desenvolvido para tornar a integração de funcionalidades de pagamento em aplicativos Flutter
  mais simples e eficiente. Ele é mantido pela comunidade Flutter e está em constante desenvolvimento.

version: 0.0.1
homepage: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  google_mlkit_barcode_scanning: ^0.7.0
  camera: ^0.10.5+2
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
